### ISSUE TITLE
Multiple fields ignored

### ISSUE THREAD

**Issue by raphihalff** [omeka/plugin-Coins#4]
If I have several omeka fields of the same kind for an certain item (say multiple creators, or multiple languages), the plugin takes only one of them.

**Comment by zerocrates** [comment]
What software are you using to consume the Coins data?

My (dim) recollection here is that the Coins plugin purposely only includes first values for each field because multiple, though allowed by the spec when using Dublin Core in a context object, wasn't well-tolerated by programs reading the coins metadata. But that could be an outdated concern by now.

**Comment by raphihalff** [comment]
I am using the zotero add on (or plugin) for firefox 85.0.2 on mac. It reads multiple authors fine on other sites (mainly library catalogs).

**Comment by zerocrates** [comment]
OK, it's Zotero. I think that's what the majority of people are using the Coins plugin for.

I think it's actually Zotero that the current setup caters to: we allow multiple values for _everything_, but Zotero doesn't. Just putting out all the values, if I'm remembering correctly, results in things like the _last_ Title being used, which is rarely what people want.

That being said, we could probably change things so the Coins plugin outputs multiple values where they _are_ supported, like for authors (and I believe subjects, I'll have to look into that more closely).

**Comment by raphihalff** [comment]
Yes, as you say, I think Zotero doesn't accept multiple values for anything BUT author/contributor. It seems, looking at the coins plugin code, that it loops through the list of dublin core elements and gets whatever value the _getElementText function returns, which I think is only one value.

**Comment by zerocrates** [comment]
Yes, you're correct on how Coins works.

It's using the `metadata` helper function under the hood, which can be changed to return all values instead of just the first one. We'd just have to add an argument or a parallel `_getAllElementTexts` method that does that instead, and split off the appropriate elements to use that method instead.

**Comment by raphihalff** [comment]
I can try to work on it submit a pull request

**Comment by zerocrates** [comment]
By all means, take a crack at it.

I think the major complication is going to be that, once you have multiple values with the same key, you can't use `http_build_query` anymore.
